version: '3'

services:
  db:
    image: 'postgres:14-alpine'
    container_name: testdb
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=my_test_db"
    restart: always
  app:
    image: tmknra/inside-test-task
    container_name: application
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
     - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_test_db"
     - "SPRING_DATASOURCE_USERNAME=postgres"
     - "SPRING_DATASOURCE_PASSWORD=root"
     - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"

